### ISSUE TITLE
Non-deterministic mining or multiple results

### ISSUE THREAD

**Issue by wschwab** [Vectorized/function-selector-miner#12]
Hi!

I have what might be a non-standard use for the miner. There's an unverified contract that I've been trying to fully reproduce the source code of, and while most of the function selectors in it appear in the public databases, there are two that don't. I can guess what the main keyword of the function name is, but haven't figured out exactly how to spin it into the specific selector.

The thing is, this project as-is will turn out a deterministic selector afaict - it'll always produce the same function name to get to the selector. I'm not too convinced that the one that I'm getting is the right one. (No, I don't think the authors appended specifically `4945026298` to the function's name.) I'm hoping maybe there's a way to either ask for multiple results (which might also be useful for minoooors so they can pick the one that is the most aesthetically pleasing to them or something), or have a switch to add some kind of salt to make results non-deterministic. Would either of those be possible?

Cheers!

**Comment by Vectorized** [comment]
Ah, unfortunately brute forcing a English selector is a much more difficult problem. 

A big part of the performance comes from the optimized uint32 to string workflow.
